stages:
    - generate
    - deploy

variables:
    GIT_SUBMODULE_STRATEGY: recursive

generate_pacman_graph:
    stage: generate
    image: node:20
    script:
        - mkdir -p dist
        - npm install -g pacman-contribution-graph
        - pacman-contribution-graph --platform gitlab --username "$CI_PROJECT_NAMESPACE" --gameTheme gitlab --output pacman-contribution-graph-light.svg
        - mv pacman-contribution-graph-light.svg dist/pacman-contribution-graph-light.svg
        - pacman-contribution-graph --platform gitlab --username "$CI_PROJECT_NAMESPACE" --gameTheme gitlab-dark --output pacman-contribution-graph-dark.svg
        - mv pacman-contribution-graph-dark.svg dist/pacman-contribution-graph-dark.svg
    artifacts:
        paths:
            - dist/pacman-contribution-graph-light.svg
            - dist/pacman-contribution-graph-dark.svg
        expire_in: 1 hour
    rules:
        - if: '$CI_PIPELINE_SOURCE == "schedule"'
        - if: '$CI_PIPELINE_SOURCE == "push"'

deploy_to_readme:
    stage: deploy
    image: alpine:latest
    script:
        - apk add --no-cache git
        - mkdir -p output
        - cp dist/pacman-contribution-graph-light.svg output/
        - cp dist/pacman-contribution-graph-dark.svg output/
        - git remote set-url origin https://gitlab-ci-token:${CI_PUSH_TOKEN}@gitlab.com/${CI_PROJECT_PATH}.git
        - git config --global user.email "pacman-bot@example.com"
        - git config --global user.name "Pacman Bot"
        - git add output/pacman-contribution-graph-light.svg output/pacman-contribution-graph-dark.svg
        - git commit -m "Update Pac-Man contribution graph [ci skip]" || echo "No changes"
        - git push origin HEAD:main
    rules:
        - if: '$CI_PIPELINE_SOURCE == "schedule"'
        - if: '$CI_PIPELINE_SOURCE == "push"'
